### ISSUE TITLE
Adding Reference

### ISSUE THREAD

**Issue by adityafeb22** [arvindshmicrosoft/SQLCallStackResolver#3]
Hey Arvind,

Sorry if it is so dumb question, I am more of a ssms guy than a vsts.

I tried fixing the reference for msdia140typelib_clr0200 and failed multiple times.

Can you help me pointing the right resource to fix this.. I have done other steps of copying the .dll files of sql 2017 to the sqlcallstackresolver sln folder. 

Thanks a lot for this effort, cant wait to start and see how the call stacks are being resolved.

**Comment by arvindshmicrosoft** [comment]
You should just use the Releases section on this repo to get a binary version which will help you skip the need to build the tool.

**Comment by arvindshmicrosoft** [comment]
FYI, Aditya: if you are trying to build locally, make sure you have VS2015 (I have not yet switched to 2017) and add a reference to C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\msdia140typelib_clr0200.dll.

**Comment by adityafeb22** [comment]
Thats the problem, i wa using vs 2017 and couldnt find testwindow folder

**Comment by adityafeb22** [comment]
Arvind,

I tried taking the latest exe and also tried to get Pdb's for sql server 2016 sp1 cu5

I also copied the .dll of sql 2017 (xecore.dll and xeventlink.dll) , I gave the path of pdb;s in path to pdb's but getting following error and not able to resolve the call stack, any help here would be greatly appreciable

Thanks again for all the knowledge and help here


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {E6756135-1E65-4D17-8576-610761398C3C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.DiaUtil..ctor(String pdbName)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.StackResolver.LocateandLoadPDBs(Dictionary`2 _diautils, String rootPaths, Boolean recurse, List`1 moduleNames)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.StackResolver.<>c__DisplayClass13_0.<ResolveCallstacks>b__0(StackWithCount currstack)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.StackResolver.ResolveCallstacks(String inputCallstackText, String symPath, Boolean searchPDBsRecursively, List`1 dllPaths, Boolean searchDLLRecursively, Boolean framesOnSingleLine, Boolean includeSourceInfo, Boolean relookupSource)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.MainForm.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {E6756135-1E65-4D17-8576-610761398C3C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.DiaUtil..ctor(String pdbName)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.StackResolver.LocateandLoadPDBs(Dictionary`2 _diautils, String rootPaths, Boolean recurse, List`1 moduleNames)
   at Microsoft.SqlServer.Utils.Misc.SQLCallStackResolver.StackResolver.<>c__DisplayClass13_0.<ResolveCallstacks>b__0(StackWithCount currstack)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SQLCallStackResolver
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
    CodeBase: file:///C:/SQLCallStackResolver/SQLCallStackResolver.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2114.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2114.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1099.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by arvindshmicrosoft** [comment]
You still need the pre-requisites as specified in v1.0 namely msdia140.dll. If you don't have Visual Studio 2015 installed, you need to download and install the Remote Tools for Visual Studio 2015 Update 3 (download from https://my.visualstudio.com).

![image](https://user-images.githubusercontent.com/16342666/36185567-a9b47462-10ee-11e8-9085-bc45e15c577b.png)

**Comment by arvindshmicrosoft** [comment]
If you still want to build with VS2017, I looked and there are many instances of the typelib in case of VS 2017 where you can find msdia140typelib_clr0200.dll (I am using VS 2017 Enterprise, there might be slight variation in other editions.)

- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools\Plugins

Aditya, I'd like to close this issue now. Hopefully you were able to unblock by installing the Remote Tools for VS2015?
